octopus:
  shards:
    america:
      adapter: sqlite3
      database: america.sqlite3
    europe:
      adapter: sqlite3
      database: europe.sqlite3
    asia:
      adapter: sqlite3
      database: asia.sqlite3